/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizQuizIdRouteImport } from './routes/quiz.$quizId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/history': typeof HistoryRoute
  '/notes': typeof NotesRoute
  '/reminders': typeof RemindersRoute
  '/stats': typeof StatsRoute
  '/upload': typeof UploadRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/history': typeof HistoryRoute
  '/notes': typeof NotesRoute
  '/reminders': typeof RemindersRoute
  '/stats': typeof StatsRoute
  '/upload': typeof UploadRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/history': typeof HistoryRoute
  '/notes': typeof NotesRoute
  '/reminders': typeof RemindersRoute
  '/stats': typeof StatsRoute
  '/upload': typeof UploadRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups'
    | '/history'
    | '/notes'
    | '/reminders'
    | '/stats'
    | '/upload'
    | '/quiz/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups'
    | '/history'
    | '/notes'
    | '/reminders'
    | '/stats'
    | '/upload'
    | '/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/groups'
    | '/history'
    | '/notes'
    | '/reminders'
    | '/stats'
    | '/upload'
    | '/quiz/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsRoute: typeof GroupsRoute
  HistoryRoute: typeof HistoryRoute
  NotesRoute: typeof NotesRoute
  RemindersRoute: typeof RemindersRoute
  StatsRoute: typeof StatsRoute
  UploadRoute: typeof UploadRoute
  QuizQuizIdRoute: typeof QuizQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsRoute: GroupsRoute,
  HistoryRoute: HistoryRoute,
  NotesRoute: NotesRoute,
  RemindersRoute: RemindersRoute,
  StatsRoute: StatsRoute,
  UploadRoute: UploadRoute,
  QuizQuizIdRoute: QuizQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
